In [90]:
import numpy as np
import scipy as sp
import math as mt
import matplotlib.pyplot as plt

In [91]:
def SS3dofDyn(x,F,param):
    m = param[0]
    I = param[1]
    l = param[2]
    b = param[3]

    state = x

    mi = 1/m
    lI = l/(2*I)
    bI = b/(2*I)

    B = np.array([[-mi,-mi,0,0,mi,mi,0,0],[0,0,-mi,-mi,0,0,mi,mi],[-lI,lI,-bI,bI,-lI,lI,-bI,bI]])

    R = np.array([[mt.cos(state[2]),mt.sin(state[2]),0],[-mt.sin(state[2]),mt.cos(state[2]),0],[0,0,1]])

    u = np.mat(R)*np.mat(B)*np.mat(F)

    A = np.zeros([6,6])
    A[0,3] = 1
    A[1,4] = 1
    A[2,5] = 1
    
    # Dynamics 

    dxdt = np.mat(A)*np.mat(np.reshape(state,(6,1))) + np.concatenate((np.array([[0],[0],[0]]),u),axis=0)
    return np.reshape(np.array(dxdt),(6))

In [92]:
xinit = np.array([[1],[0],[0],[0],[0],[0]])
x0 = np.reshape(xinit,(6))
F = np.array([[1],[0],[0],[0],[0],[0],[0],[0]])
param = np.array([1,1,1,1])
t = np.linspace(0, 10, 100)

In [93]:
x0

array([1, 0, 0, 0, 0, 0])

In [94]:
m = param[0]
I = param[1]
l = param[2]
b = param[3]

mi = 1/m
lI = l/(2*I)
bI = b/(2*I)

In [95]:
x0

array([1, 0, 0, 0, 0, 0])

In [96]:
SS3dofDyn(x0,F,param)

array([ 0. ,  0. ,  0. , -1. ,  0. , -0.5])

In [97]:
n = len(t)
x = np.zeros([6,n])

In [98]:
dx = SS3dofDyn(np.reshape(x[:,5],(6,1)),F,param)

In [99]:
dx

array([ 0. ,  0. ,  0. , -1. ,  0. , -0.5])

In [100]:
np.reshape(np.array(dx),(6))

array([ 0. ,  0. ,  0. , -1. ,  0. , -0.5])

In [112]:
x[:,5] = x0

In [113]:
x[:,5]

array([1., 0., 0., 0., 0., 0.])

In [103]:
def EulerInt(dxdt,dt,xt):
    xt1 = xt + dxdt*dt   
    return xt1

In [104]:
b = EulerInt(SS3dofDyn(x0,F,param),t[1]-t[0],x0)

In [105]:
SS3dofDyn(x0,F,param)

array([ 0. ,  0. ,  0. , -1. ,  0. , -0.5])

In [108]:
b

array([ 1.        ,  0.        ,  0.        , -0.1010101 ,  0.        ,
       -0.05050505])

In [109]:
b[1]

0.0

In [110]:
b[0]

1.0